name: Victor Steinborn
email: vsteinborn@cis-muenchen.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  VSteinborn
linkedin_endurl: victor-steinborn-601455255

collections:
  tagged:
    output: true
    permalink: /tagged/:path/
  education:
    output: true
    permalink: /education/:path/
  projects:
    output: true
    permalink: /projects/:path/
  work_experience:
    output: true
    permalink: /work_experience/:path/

# Build settings
markdown: kramdown
permalink: /entries/:year/:month/:day/:title
highlighter: rouge
